version: '3.4'

services:

  selenium:
    image: selenium/standalone-chrome
    shm_size: 2gb
    ports:
    - 4444:4444

  autotest2master:
    image: test:v1
    container_name: autotest
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - /home/autotest2-master/logs:/app/logs
      - /home/jenkins/jenkins-compose/workspace/python_test/allure-results:/app/test_results